[tool.black]
line-length=79
exclude=''


[tool.pytest.ini_options]
asyncio_mode='auto'
log_cli_level = "DEBUG"

[tool.mypy]
strict=true
plugins=["faviorm/mypy_plugin.py"]
exclude = "__tests__/test_mypy_types.py"
